---
# After these tasks complete sshd may be running on a different port, denying root login,
# or only accepting pubkeys. If you can't run any further Ansible commands perhaps
# your hosts file or cli command hasn't accounted for the above issues

- name: Harden sshd configuration
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backrefs: yes
  with_items:
    - regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication {{ common_ssh_password_authentication }}"
    - regexp: "^#?PermitRootLogin"
      line: "PermitRootLogin {{ common_ssh_permit_root_login }}"
  notify:
    - reload sshd

# A custom SSH port requires multiple changes, including configuring SELinux
# and firewalld to accept the new port
- name: "Configure ssh for port {{ common_ssh_port }}"
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: "^#?Port"
    line: "Port {{ common_ssh_port }}"
  register: port_command
  notify:
    - reload sshd

# Idempotent SELinux ssh port modifications
# Adapted from: http://jensd.be/587/linux/tips-tricks-for-ansible
- name: "Validate SELinux configuraiton of ssh port {{ common_ssh_port }}"
  shell: semanage port -l | egrep "^ssh_port_t" | egrep "\b{{ common_ssh_port }}\b"
  register: selinux_command
  changed_when: selinux_command.stdout.find("{{ common_ssh_port }}") == -1
  failed_when: False
  when: common_selinux_mode != 'disabled' and port_command.changed

- name: "Configure SELinux for ssh port {{ common_ssh_port }}"
  command: semanage port -a -t ssh_port_t -p tcp {{ common_ssh_port }}
  when: selinux_command.changed
